In [1]:
import pandas as pd
pd.set_option('display.max_columns', 100)
import numpy as np

from matplotlib import pyplot as plt
%matplotlib inline

import seaborn as sns

In [2]:
df = pd.read_excel('CANADA-PR-Citz.xlsx')
df.head(12)

,"Canada - Admissions of Permanent Residents by Country of Citizenship, January 2015 - January 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,...,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,Unnamed: 144,Unnamed: 145,Unnamed: 146,Unnamed: 147,Unnamed: 148,Unnamed: 149,Unnamed: 150,Unnamed: 151,Unnamed: 152,Unnamed: 153,Unnamed: 154,Unnamed: 155,Unnamed: 156
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country of Citizenship,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,NaN,NaN
2,NaN,Q1,NaN,NaN,NaN,Q2,NaN,NaN,NaN,Q3,NaN,NaN,NaN,Q4,NaN,NaN,NaN,2015 Total,Q1,NaN,NaN,NaN,Q2,NaN,NaN,NaN,Q3,NaN,NaN,NaN,Q4,NaN,NaN,NaN,2016 Total,Q1,NaN,NaN,NaN,Q2,NaN,NaN,NaN,Q3,NaN,NaN,NaN,Q4,NaN,NaN,...,Q2,NaN,NaN,NaN,Q3,NaN,NaN,NaN,Q4,NaN,NaN,NaN,2021 Total,Q1,NaN,NaN,NaN,Q2,NaN,NaN,NaN,Q3,NaN,NaN,NaN,Q4,NaN,NaN,NaN,2022 Total,Q1,NaN,NaN,NaN,Q2,NaN,NaN,NaN,Q3,NaN,NaN,NaN,Q4,NaN,NaN,NaN,2023 Total,Q1,NaN,2024 Total
3,NaN,Jan,Feb,Mar,Q1 Total,Apr,May,Jun,Q2 Total,Jul,Aug,Sep,Q3 Total,Oct,Nov,Dec,Q4 Total,NaN,Jan,Feb,Mar,Q1 Total,Apr,May,Jun,Q2 Total,Jul,Aug,Sep,Q3 Total,Oct,Nov,Dec,Q4 Total,NaN,Jan,Feb,Mar,Q1 Total,Apr,May,Jun,Q2 Total,Jul,Aug,Sep,Q3 Total,Oct,Nov,Dec,...,Apr,May,Jun,Q2 Total,Jul,Aug,Sep,Q3 Total,Oct,Nov,Dec,Q4 Total,NaN,Jan,Feb,Mar,Q1 Total,Apr,May,Jun,Q2 Total,Jul,Aug,Sep,Q3 Total,Oct,Nov,Dec,Q4 Total,NaN,Jan,Feb,Mar,Q1 Total,Apr,May,Jun,Q2 Total,Jul,Aug,Sep,Q3 Total,Oct,Nov,Dec,Q4 Total,NaN,Jan,Q1 Total,NaN
4,Afghanistan,90,125,220,435,135,220,195,555,250,145,375,770,270,335,265,870,"2,630",215,295,260,765,285,200,255,740,210,125,275,610,255,160,120,535,"2,650",230,375,325,930,330,210,210,750,310,280,235,820,290,405,260,...,140,150,180,475,180,"1,010","1,535","2,725","1,130","1,265","2,430","4,825","8,570",865,"1,650","2,075","4,590","2,215","2,475","2,145","6,835","1,130","1,225","3,520","5,875","2,660","2,240","1,545","6,450","23,750",715,875,"1,320","2,905","1,110","2,225","1,430","4,765","2,000","1,250","2,210","5,460","1,400","3,465","2,180","7,045","20,180","1,815","1,815","1,815"
5,Albania,15,25,50,90,45,45,75,165,45,65,60,170,35,50,55,140,565,50,30,65,145,45,60,45,150,30,40,40,110,40,25,40,105,510,40,50,80,170,70,60,65,190,75,30,70,175,35,35,40,...,35,35,45,115,60,55,75,190,45,40,45,130,550,50,50,65,165,75,40,50,165,35,40,55,125,30,15,20,65,520,85,60,70,215,25,65,45,135,75,70,30,175,40,40,50,125,655,110,110,110
6,Algeria,80,125,235,440,255,340,280,875,310,280,355,940,225,170,175,570,"2,830",95,100,215,410,300,330,245,880,585,255,220,"1,055",190,130,150,475,"2,820",140,120,270,530,280,210,250,740,505,205,215,925,145,145,150,...,90,110,245,445,590,285,280,"1,155",365,315,325,"1,010","3,080",200,360,530,"1,090",395,630,710,"1,735","1,085",390,735,"2,205",490,300,350,"1,140","6,175",225,265,320,805,285,510,530,"1,325",875,325,760,"1,960",540,335,280,"1,160","5,245",400,400,400
7,Andorra,0,0,0,0,--,0,0,--,0,--,0,--,0,0,0,0,--,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,--,0,0,--,0,0,0,0,--,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,--,--,0,0,0,0,0,0,0,0,0,0,0,0,--,0,0,0
8,Angola,--,0,--,--,10,--,--,15,--,--,--,5,0,--,5,10,30,--,5,--,10,0,10,--,15,--,--,--,5,--,--,0,--,30,5,--,--,10,5,--,5,15,10,--,0,10,--,--,--,...,5,--,--,15,15,15,15,45,25,20,15,60,150,15,25,20,60,50,30,25,105,30,20,10,60,--,5,--,15,240,25,35,25,85,25,15,10,50,10,5,5,25,25,15,35,75,235,20,20,20
9,Antigua and Barbuda,--,5,10,20,--,--,5,10,5,5,5,20,--,--,--,5,55,0,10,--,10,--,--,--,10,5,--,10,15,--,--,--,10,45,5,10,5,25,10,10,--,20,10,--,--,15,5,--,10,...,5,5,5,20,10,5,20,35,15,15,15,40,120,10,5,10,25,10,10,5,25,15,10,10,35,10,--,5,20,105,25,10,10,45,10,5,10,30,10,15,5,30,--,5,5,15,120,--,--,--
10,Argentina,10,15,15,40,25,25,20,65,25,20,20,65,10,20,25,55,225,30,15,20,70,35,40,20,100,20,25,15,60,20,10,10,35,265,30,15,15,60,15,15,20,50,25,15,20,55,20,20,25,...,20,20,50,90,25,40,35,105,50,45,55,145,410,30,35,55,120,30,25,25,80,45,35,30,110,15,20,15,50,360,55,50,45,150,30,60,65,155,30,40,10,80,25,15,65,100,485,55,55,55
11,Armenia,10,10,10,25,20,15,40,75,45,50,40,130,25,15,30,70,305,10,20,20,50,35,15,40,90,35,45,60,140,45,10,20,70,350,10,30,30,70,30,15,30,75,30,5,15,50,20,15,20,...,5,15,5,25,10,5,15,35,5,--,10,20,95,5,20,--,30,15,5,15,40,15,10,10,30,20,5,15,40,140,15,15,15,40,5,15,35,55,30,15,25,70,30,25,15,70,240,10,10,10

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Columns: 157 entries, Canada - Admissions of Permanent Residents by Country of Citizenship, January 2015 - January 2024 to Unnamed: 156
dtypes: object(157)
memory usage: 277.3+ KB

In [4]:
for i in range(1,156):
    month = ["Jan","Feb","Mar","Q1Total","Apr","May","Jun","Q2Total","July","Aug","Sep","Q3Total","Oct","Nov","Dec","Q4total","YearTotal"]
    df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]

C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]
C:\Users\PRIYA\AppData\Local\Temp\ipykernel_21580\2950358298.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[str(2015+int((i-1)/17))+month[(i+16)%17]] = df["Unnamed: "+str(i)]

In [5]:
df.head()

,"Canada - Admissions of Permanent Residents by Country of Citizenship, January 2015 - January 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,...,2021Q1Total,2021Apr,2021May,2021Jun,2021Q2Total,2021July,2021Aug,2021Sep,2021Q3Total,2021Oct,2021Nov,2021Dec,2021Q4total,2021YearTotal,2022Jan,2022Feb,2022Mar,2022Q1Total,2022Apr,2022May,2022Jun,2022Q2Total,2022July,2022Aug,2022Sep,2022Q3Total,2022Oct,2022Nov,2022Dec,2022Q4total,2022YearTotal,2023Jan,2023Feb,2023Mar,2023Q1Total,2023Apr,2023May,2023Jun,2023Q2Total,2023July,2023Aug,2023Sep,2023Q3Total,2023Oct,2023Nov,2023Dec,2023Q4total,2023YearTotal,2024Jan,2024Feb
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country of Citizenship,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,NaN
2,NaN,Q1,NaN,NaN,NaN,Q2,NaN,NaN,NaN,Q3,NaN,NaN,NaN,Q4,NaN,NaN,NaN,2015 Total,Q1,NaN,NaN,NaN,Q2,NaN,NaN,NaN,Q3,NaN,NaN,NaN,Q4,NaN,NaN,NaN,2016 Total,Q1,NaN,NaN,NaN,Q2,NaN,NaN,NaN,Q3,NaN,NaN,NaN,Q4,NaN,NaN,...,NaN,Q2,NaN,NaN,NaN,Q3,NaN,NaN,NaN,Q4,NaN,NaN,NaN,2021 Total,Q1,NaN,NaN,NaN,Q2,NaN,NaN,NaN,Q3,NaN,NaN,NaN,Q4,NaN,NaN,NaN,2022 Total,Q1,NaN,NaN,NaN,Q2,NaN,NaN,NaN,Q3,NaN,NaN,NaN,Q4,NaN,NaN,NaN,2023 Total,Q1,NaN
3,NaN,Jan,Feb,Mar,Q1 Total,Apr,May,Jun,Q2 Total,Jul,Aug,Sep,Q3 Total,Oct,Nov,Dec,Q4 Total,NaN,Jan,Feb,Mar,Q1 Total,Apr,May,Jun,Q2 Total,Jul,Aug,Sep,Q3 Total,Oct,Nov,Dec,Q4 Total,NaN,Jan,Feb,Mar,Q1 Total,Apr,May,Jun,Q2 Total,Jul,Aug,Sep,Q3 Total,Oct,Nov,Dec,...,Q1 Total,Apr,May,Jun,Q2 Total,Jul,Aug,Sep,Q3 Total,Oct,Nov,Dec,Q4 Total,NaN,Jan,Feb,Mar,Q1 Total,Apr,May,Jun,Q2 Total,Jul,Aug,Sep,Q3 Total,Oct,Nov,Dec,Q4 Total,NaN,Jan,Feb,Mar,Q1 Total,Apr,May,Jun,Q2 Total,Jul,Aug,Sep,Q3 Total,Oct,Nov,Dec,Q4 Total,NaN,Jan,Q1 Total
4,Afghanistan,90,125,220,435,135,220,195,555,250,145,375,770,270,335,265,870,"2,630",215,295,260,765,285,200,255,740,210,125,275,610,255,160,120,535,"2,650",230,375,325,930,330,210,210,750,310,280,235,820,290,405,260,...,545,140,150,180,475,180,"1,010","1,535","2,725","1,130","1,265","2,430","4,825","8,570",865,"1,650","2,075","4,590","2,215","2,475","2,145","6,835","1,130","1,225","3,520","5,875","2,660","2,240","1,545","6,450","23,750",715,875,"1,320","2,905","1,110","2,225","1,430","4,765","2,000","1,250","2,210","5,460","1,400","3,465","2,180","7,045","20,180","1,815","1,815"

In [6]:
df = df.drop([0,1,2,3])
df.head()

,"Canada - Admissions of Permanent Residents by Country of Citizenship, January 2015 - January 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,...,2021Q1Total,2021Apr,2021May,2021Jun,2021Q2Total,2021July,2021Aug,2021Sep,2021Q3Total,2021Oct,2021Nov,2021Dec,2021Q4total,2021YearTotal,2022Jan,2022Feb,2022Mar,2022Q1Total,2022Apr,2022May,2022Jun,2022Q2Total,2022July,2022Aug,2022Sep,2022Q3Total,2022Oct,2022Nov,2022Dec,2022Q4total,2022YearTotal,2023Jan,2023Feb,2023Mar,2023Q1Total,2023Apr,2023May,2023Jun,2023Q2Total,2023July,2023Aug,2023Sep,2023Q3Total,2023Oct,2023Nov,2023Dec,2023Q4total,2023YearTotal,2024Jan,2024Feb
4,Afghanistan,90,125,220,435,135,220,195,555,250,145,375,770,270,335,265,870,"2,630",215,295,260,765,285,200,255,740,210,125,275,610,255,160,120,535,"2,650",230,375,325,930,330,210,210,750,310,280,235,820,290,405,260,...,545,140,150,180,475,180,"1,010","1,535","2,725","1,130","1,265","2,430","4,825","8,570",865,"1,650","2,075","4,590","2,215","2,475","2,145","6,835","1,130","1,225","3,520","5,875","2,660","2,240","1,545","6,450","23,750",715,875,"1,320","2,905","1,110","2,225","1,430","4,765","2,000","1,250","2,210","5,460","1,400","3,465","2,180","7,045","20,180","1,815","1,815"
5,Albania,15,25,50,90,45,45,75,165,45,65,60,170,35,50,55,140,565,50,30,65,145,45,60,45,150,30,40,40,110,40,25,40,105,510,40,50,80,170,70,60,65,190,75,30,70,175,35,35,40,...,115,35,35,45,115,60,55,75,190,45,40,45,130,550,50,50,65,165,75,40,50,165,35,40,55,125,30,15,20,65,520,85,60,70,215,25,65,45,135,75,70,30,175,40,40,50,125,655,110,110
6,Algeria,80,125,235,440,255,340,280,875,310,280,355,940,225,170,175,570,"2,830",95,100,215,410,300,330,245,880,585,255,220,"1,055",190,130,150,475,"2,820",140,120,270,530,280,210,250,740,505,205,215,925,145,145,150,...,465,90,110,245,445,590,285,280,"1,155",365,315,325,"1,010","3,080",200,360,530,"1,090",395,630,710,"1,735","1,085",390,735,"2,205",490,300,350,"1,140","6,175",225,265,320,805,285,510,530,"1,325",875,325,760,"1,960",540,335,280,"1,160","5,245",400,400
7,Andorra,0,0,0,0,--,0,0,--,0,--,0,--,0,0,0,0,--,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,--,0,0,--,0,0,0,0,--,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,--,--,0,0,0,0,0,0,0,0,0,0,0,0,--,0,0
8,Angola,--,0,--,--,10,--,--,15,--,--,--,5,0,--,5,10,30,--,5,--,10,0,10,--,15,--,--,--,5,--,--,0,--,30,5,--,--,10,5,--,5,15,10,--,0,10,--,--,--,...,35,5,--,--,15,15,15,15,45,25,20,15,60,150,15,25,20,60,50,30,25,105,30,20,10,60,--,5,--,15,240,25,35,25,85,25,15,10,50,10,5,5,25,25,15,35,75,235,20,20

In [7]:
df = df.drop(df.iloc[:,1:156],axis = 1)
df.head()

,"Canada - Admissions of Permanent Residents by Country of Citizenship, January 2015 - January 2024",Unnamed: 156,2015Jan,2015Feb,2015Mar,2015Q1Total,2015Apr,2015May,2015Jun,2015Q2Total,2015July,2015Aug,2015Sep,2015Q3Total,2015Oct,2015Nov,2015Dec,2015Q4total,2015YearTotal,2016Jan,2016Feb,2016Mar,2016Q1Total,2016Apr,2016May,2016Jun,2016Q2Total,2016July,2016Aug,2016Sep,2016Q3Total,2016Oct,2016Nov,2016Dec,2016Q4total,2016YearTotal,2017Jan,2017Feb,2017Mar,2017Q1Total,2017Apr,2017May,2017Jun,2017Q2Total,2017July,2017Aug,2017Sep,2017Q3Total,2017Oct,2017Nov,...,2021Q1Total,2021Apr,2021May,2021Jun,2021Q2Total,2021July,2021Aug,2021Sep,2021Q3Total,2021Oct,2021Nov,2021Dec,2021Q4total,2021YearTotal,2022Jan,2022Feb,2022Mar,2022Q1Total,2022Apr,2022May,2022Jun,2022Q2Total,2022July,2022Aug,2022Sep,2022Q3Total,2022Oct,2022Nov,2022Dec,2022Q4total,2022YearTotal,2023Jan,2023Feb,2023Mar,2023Q1Total,2023Apr,2023May,2023Jun,2023Q2Total,2023July,2023Aug,2023Sep,2023Q3Total,2023Oct,2023Nov,2023Dec,2023Q4total,2023YearTotal,2024Jan,2024Feb
4,Afghanistan,"1,815",90,125,220,435,135,220,195,555,250,145,375,770,270,335,265,870,"2,630",215,295,260,765,285,200,255,740,210,125,275,610,255,160,120,535,"2,650",230,375,325,930,330,210,210,750,310,280,235,820,290,405,...,545,140,150,180,475,180,"1,010","1,535","2,725","1,130","1,265","2,430","4,825","8,570",865,"1,650","2,075","4,590","2,215","2,475","2,145","6,835","1,130","1,225","3,520","5,875","2,660","2,240","1,545","6,450","23,750",715,875,"1,320","2,905","1,110","2,225","1,430","4,765","2,000","1,250","2,210","5,460","1,400","3,465","2,180","7,045","20,180","1,815","1,815"
5,Albania,110,15,25,50,90,45,45,75,165,45,65,60,170,35,50,55,140,565,50,30,65,145,45,60,45,150,30,40,40,110,40,25,40,105,510,40,50,80,170,70,60,65,190,75,30,70,175,35,35,...,115,35,35,45,115,60,55,75,190,45,40,45,130,550,50,50,65,165,75,40,50,165,35,40,55,125,30,15,20,65,520,85,60,70,215,25,65,45,135,75,70,30,175,40,40,50,125,655,110,110
6,Algeria,400,80,125,235,440,255,340,280,875,310,280,355,940,225,170,175,570,"2,830",95,100,215,410,300,330,245,880,585,255,220,"1,055",190,130,150,475,"2,820",140,120,270,530,280,210,250,740,505,205,215,925,145,145,...,465,90,110,245,445,590,285,280,"1,155",365,315,325,"1,010","3,080",200,360,530,"1,090",395,630,710,"1,735","1,085",390,735,"2,205",490,300,350,"1,140","6,175",225,265,320,805,285,510,530,"1,325",875,325,760,"1,960",540,335,280,"1,160","5,245",400,400
7,Andorra,0,0,0,0,0,--,0,0,--,0,--,0,--,0,0,0,0,--,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,--,0,0,--,0,0,0,0,--,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,--,--,0,0,0,0,0,0,0,0,0,0,0,0,--,0,0
8,Angola,20,--,0,--,--,10,--,--,15,--,--,--,5,0,--,5,10,30,--,5,--,10,0,10,--,15,--,--,--,5,--,--,0,--,30,5,--,--,10,5,--,5,15,10,--,0,10,--,--,...,35,5,--,--,15,15,15,15,45,25,20,15,60,150,15,25,20,60,50,30,25,105,30,20,10,60,--,5,--,15,240,25,35,25,85,25,15,10,50,10,5,5,25,25,15,35,75,235,20,20

In [8]:
df = df.drop(columns = ["Unnamed: 156"])
df.head()

,"Canada - Admissions of Permanent Residents by Country of Citizenship, January 2015 - January 2024",2015Jan,2015Feb,2015Mar,2015Q1Total,2015Apr,2015May,2015Jun,2015Q2Total,2015July,2015Aug,2015Sep,2015Q3Total,2015Oct,2015Nov,2015Dec,2015Q4total,2015YearTotal,2016Jan,2016Feb,2016Mar,2016Q1Total,2016Apr,2016May,2016Jun,2016Q2Total,2016July,2016Aug,2016Sep,2016Q3Total,2016Oct,2016Nov,2016Dec,2016Q4total,2016YearTotal,2017Jan,2017Feb,2017Mar,2017Q1Total,2017Apr,2017May,2017Jun,2017Q2Total,2017July,2017Aug,2017Sep,2017Q3Total,2017Oct,2017Nov,2017Dec,...,2021Q1Total,2021Apr,2021May,2021Jun,2021Q2Total,2021July,2021Aug,2021Sep,2021Q3Total,2021Oct,2021Nov,2021Dec,2021Q4total,2021YearTotal,2022Jan,2022Feb,2022Mar,2022Q1Total,2022Apr,2022May,2022Jun,2022Q2Total,2022July,2022Aug,2022Sep,2022Q3Total,2022Oct,2022Nov,2022Dec,2022Q4total,2022YearTotal,2023Jan,2023Feb,2023Mar,2023Q1Total,2023Apr,2023May,2023Jun,2023Q2Total,2023July,2023Aug,2023Sep,2023Q3Total,2023Oct,2023Nov,2023Dec,2023Q4total,2023YearTotal,2024Jan,2024Feb
4,Afghanistan,90,125,220,435,135,220,195,555,250,145,375,770,270,335,265,870,"2,630",215,295,260,765,285,200,255,740,210,125,275,610,255,160,120,535,"2,650",230,375,325,930,330,210,210,750,310,280,235,820,290,405,260,...,545,140,150,180,475,180,"1,010","1,535","2,725","1,130","1,265","2,430","4,825","8,570",865,"1,650","2,075","4,590","2,215","2,475","2,145","6,835","1,130","1,225","3,520","5,875","2,660","2,240","1,545","6,450","23,750",715,875,"1,320","2,905","1,110","2,225","1,430","4,765","2,000","1,250","2,210","5,460","1,400","3,465","2,180","7,045","20,180","1,815","1,815"
5,Albania,15,25,50,90,45,45,75,165,45,65,60,170,35,50,55,140,565,50,30,65,145,45,60,45,150,30,40,40,110,40,25,40,105,510,40,50,80,170,70,60,65,190,75,30,70,175,35,35,40,...,115,35,35,45,115,60,55,75,190,45,40,45,130,550,50,50,65,165,75,40,50,165,35,40,55,125,30,15,20,65,520,85,60,70,215,25,65,45,135,75,70,30,175,40,40,50,125,655,110,110
6,Algeria,80,125,235,440,255,340,280,875,310,280,355,940,225,170,175,570,"2,830",95,100,215,410,300,330,245,880,585,255,220,"1,055",190,130,150,475,"2,820",140,120,270,530,280,210,250,740,505,205,215,925,145,145,150,...,465,90,110,245,445,590,285,280,"1,155",365,315,325,"1,010","3,080",200,360,530,"1,090",395,630,710,"1,735","1,085",390,735,"2,205",490,300,350,"1,140","6,175",225,265,320,805,285,510,530,"1,325",875,325,760,"1,960",540,335,280,"1,160","5,245",400,400
7,Andorra,0,0,0,0,--,0,0,--,0,--,0,--,0,0,0,0,--,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,--,0,0,--,0,0,0,0,--,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,--,--,0,0,0,0,0,0,0,0,0,0,0,0,--,0,0
8,Angola,--,0,--,--,10,--,--,15,--,--,--,5,0,--,5,10,30,--,5,--,10,0,10,--,15,--,--,--,5,--,--,0,--,30,5,--,--,10,5,--,5,15,10,--,0,10,--,--,--,...,35,5,--,--,15,15,15,15,45,25,20,15,60,150,15,25,20,60,50,30,25,105,30,20,10,60,--,5,--,15,240,25,35,25,85,25,15,10,50,10,5,5,25,25,15,35,75,235,20,20

In [9]:
df.tail(12)

,"Canada - Admissions of Permanent Residents by Country of Citizenship, January 2015 - January 2024",2015Jan,2015Feb,2015Mar,2015Q1Total,2015Apr,2015May,2015Jun,2015Q2Total,2015July,2015Aug,2015Sep,2015Q3Total,2015Oct,2015Nov,2015Dec,2015Q4total,2015YearTotal,2016Jan,2016Feb,2016Mar,2016Q1Total,2016Apr,2016May,2016Jun,2016Q2Total,2016July,2016Aug,2016Sep,2016Q3Total,2016Oct,2016Nov,2016Dec,2016Q4total,2016YearTotal,2017Jan,2017Feb,2017Mar,2017Q1Total,2017Apr,2017May,2017Jun,2017Q2Total,2017July,2017Aug,2017Sep,2017Q3Total,2017Oct,2017Nov,2017Dec,...,2021Q1Total,2021Apr,2021May,2021Jun,2021Q2Total,2021July,2021Aug,2021Sep,2021Q3Total,2021Oct,2021Nov,2021Dec,2021Q4total,2021YearTotal,2022Jan,2022Feb,2022Mar,2022Q1Total,2022Apr,2022May,2022Jun,2022Q2Total,2022July,2022Aug,2022Sep,2022Q3Total,2022Oct,2022Nov,2022Dec,2022Q4total,2022YearTotal,2023Jan,2023Feb,2023Mar,2023Q1Total,2023Apr,2023May,2023Jun,2023Q2Total,2023July,2023Aug,2023Sep,2023Q3Total,2023Oct,2023Nov,2023Dec,2023Q4total,2023YearTotal,2024Jan,2024Feb
214,"Virgin Islands, British",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
215,Western Sahara,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,--,0,0,--,0,0,0,0,0,0,0,0,0,0,0,0,--,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,--,0,0,0,0,0,0,0,0,0,0,0,0,--,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
216,Yemen,15,5,25,45,20,15,20,55,15,15,20,50,20,20,15,55,205,15,5,15,40,--,45,25,70,10,10,15,35,10,5,--,20,160,10,10,15,40,20,25,35,80,45,20,10,80,20,15,15,...,440,90,90,85,260,70,100,145,320,155,115,95,360,"1,380",85,80,90,255,65,90,70,230,80,35,75,190,70,35,45,150,820,80,50,45,180,30,45,80,155,55,70,50,170,45,50,55,150,650,70,70
217,Zambia,--,0,--,--,--,--,--,10,--,10,5,20,5,--,10,20,55,0,--,5,5,5,5,10,20,--,5,--,10,5,--,5,15,55,15,10,--,25,5,10,10,25,5,10,--,15,5,--,15,...,20,--,10,10,25,10,5,--,20,10,10,10,30,95,5,5,10,20,--,10,5,20,15,10,--,30,5,5,--,15,85,20,10,10,40,--,5,5,15,10,--,5,15,--,5,10,20,90,10,10
218,Zimbabwe,15,15,25,55,15,20,15,50,25,20,20,65,30,15,15,60,230,25,15,25,65,25,50,25,105,10,20,20,50,20,30,15,65,280,35,20,45,100,30,35,40,100,55,35,25,115,20,40,40,...,90,30,20,50,100,45,55,60,160,40,40,80,165,510,50,70,65,180,60,50,60,165,40,60,65,165,35,25,35,95,605,70,60,40,170,50,55,45,150,40,50,25,110,30,30,60,120,555,50,50
219,Country not stated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,--,--,0,0,0,0,--,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
220,Total,"12,910","16,440","21,770","51,125","21,165","23,895","27,025","72,090","27,770","24,350","26,770","78,890","23,990","20,855","24,890","69,735","271,840","27,280","32,035","26,925","86,235","28,125","29,460","30,710","88,295","26,485","21,265","20,480","68,230","18,320","16,205","19,085","53,610","296,375","21,890","22,825","28,120","72,835","25,120","25,435","27,460","78,015","25,770","22,210","22,155","70,135","21,175","20,155","24,220",...,"70,495","21,165","17,470","35,800","74,440","39,750","37,910","45,255","122,915","46,505","47,625","44,065","138,200","406,050","35,450","37,365","40,990","113,805","36,370","37,995","43,955","118,320","43,350","34,150","44,705","122,205","33,740","26,100","23,460","83,295","437,625","50,945","49,670","44,875","145,485","29,565","46,005","42,355","117,925","40,705","35,095","32,190","107,990","33,630","29,505","37,240","100,375","471,770","47,660","47,660"
221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,Notes:\n— Please note that all values between ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,"Source: IRCC, January 31, 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df = df.drop([221,222,223,224,225])
df.tail(12)

,"Canada - Admissions of Permanent Residents by Country of Citizenship, January 2015 - January 2024",2015Jan,2015Feb,2015Mar,2015Q1Total,2015Apr,2015May,2015Jun,2015Q2Total,2015July,2015Aug,2015Sep,2015Q3Total,2015Oct,2015Nov,2015Dec,2015Q4total,2015YearTotal,2016Jan,2016Feb,2016Mar,2016Q1Total,2016Apr,2016May,2016Jun,2016Q2Total,2016July,2016Aug,2016Sep,2016Q3Total,2016Oct,2016Nov,2016Dec,2016Q4total,2016YearTotal,2017Jan,2017Feb,2017Mar,2017Q1Total,2017Apr,2017May,2017Jun,2017Q2Total,2017July,2017Aug,2017Sep,2017Q3Total,2017Oct,2017Nov,2017Dec,...,2021Q1Total,2021Apr,2021May,2021Jun,2021Q2Total,2021July,2021Aug,2021Sep,2021Q3Total,2021Oct,2021Nov,2021Dec,2021Q4total,2021YearTotal,2022Jan,2022Feb,2022Mar,2022Q1Total,2022Apr,2022May,2022Jun,2022Q2Total,2022July,2022Aug,2022Sep,2022Q3Total,2022Oct,2022Nov,2022Dec,2022Q4total,2022YearTotal,2023Jan,2023Feb,2023Mar,2023Q1Total,2023Apr,2023May,2023Jun,2023Q2Total,2023July,2023Aug,2023Sep,2023Q3Total,2023Oct,2023Nov,2023Dec,2023Q4total,2023YearTotal,2024Jan,2024Feb
209,Uruguay,--,--,--,10,--,10,0,10,--,10,--,10,--,5,--,15,45,--,--,10,15,--,--,5,10,10,10,--,20,--,5,--,10,55,--,--,--,5,5,--,0,10,0,--,--,--,--,--,--,...,15,--,5,5,10,10,5,5,20,10,10,5,25,75,10,5,10,25,--,--,10,15,10,--,--,15,5,0,0,5,65,10,5,10,30,0,10,10,20,10,5,--,15,--,--,--,10,75,15,15
210,Uzbekistan,5,5,25,35,15,10,20,50,15,5,25,50,20,20,20,60,190,10,5,20,35,20,25,35,80,20,25,20,65,15,10,5,30,210,10,10,10,30,10,30,30,65,10,15,5,30,15,15,25,...,40,5,10,10,25,15,5,5,30,5,10,10,25,120,5,--,10,20,--,20,15,35,10,15,--,30,15,5,5,25,115,5,15,15,40,20,20,15,55,25,20,10,60,5,20,15,40,190,25,25
211,Vanuatu,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,--,--,--,0,0,0,0,0,0,0,0,0,0,0,0,--,0,0
212,Venezuela,40,40,75,160,80,70,90,235,65,115,80,260,95,85,75,260,915,80,70,90,240,115,115,130,360,85,100,60,245,65,45,55,165,"1,010",60,70,80,210,80,75,115,270,110,85,75,270,80,75,105,...,785,250,195,195,640,170,180,220,575,175,240,205,620,"2,625",170,150,155,475,130,175,135,440,170,110,125,405,85,75,60,225,"1,545",185,125,110,420,95,145,140,380,105,145,75,325,95,50,115,265,"1,390",145,145
213,Vietnam,90,165,180,435,155,150,190,490,250,205,430,885,300,270,215,785,"2,595",220,215,290,725,205,205,255,665,250,165,185,600,160,125,175,460,"2,450",145,195,250,590,200,210,315,725,240,230,190,665,185,140,200,...,875,320,230,500,"1,045",610,540,595,"1,745",675,800,615,"2,090","5,755",575,565,580,"1,720",535,460,635,"1,630",600,490,460,"1,555",275,120,160,560,"5,460",915,865,620,"2,405",330,705,525,"1,560",580,470,355,"1,405",325,290,620,"1,235","6,605",825,825
214,"Virgin Islands, British",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
215,Western Sahara,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,--,0,0,--,0,0,0,0,0,0,0,0,0,0,0,0,--,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,--,0,0,0,0,0,0,0,0,0,0,0,0,--,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
216,Yemen,15,5,25,45,20,15,20,55,15,15,20,50,20,20,15,55,205,15,5,15,40,--,45,25,70,10,10,15,35,10,5,--,20,160,10,10,15,40,20,25,35,80,45,20,10,80,20,15,15,...,440,90,90,85,260,70,100,145,320,155,115,95,360,"1,380",85,80,90,255,65,90,70,230,80,35,75,190,70,35,45,150,820,80,50,45,180,30,45,80,155,55,70,50,170,45,50,55,150,650,70,70
217,Zambia,--,0,--,--,--,--,--,10,--,10,5,20,5,--,10,20,55,0,--,5,5,5,5,10,20,--,5,--,10,5,--,5,15,55,15,10,--,25,5,10,10,25,5,10,--,15,5,--,15,...,20,--,10,10,25,10,5,--,20,10,10,10,30,95,5,5,10,20,--,10,5,20,15,10,--,30,5,5,--,15,85,20,10,10,40,--,5,5,15,10,--,5,15,--,5,10,20,90,10,10
218,Zimbabwe,15,15,25,55,15,20,15,50,25,20,20,65,30,15,15,60,230,25,15,25,65,25,50,25,105,10,20,20,50,20,30,15,65,280,35,20,45,100,30,35,40,100,55,35,25,115,20,40,40,...,90,30,20,50,100,45,55,60,160,40,40,80,165,510,50,70,65,180,60,50,60,165,40,60,65,165,35,25,35,95,605,70,60,40,170,50,55,45,150,40,50,25,110,30,30,60,120,555,50,50
219,Country not stated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,--,--,0,0,0,0,--,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
220,Total,"12,910","16,440","21,770","51,125","21,165","23,895","27,025","72,090","27,770","24,350","26,770","78,890","23,990","20,855","24,890","69,735","271,840","27,280","32,035","26,925","86,235","28,125","29,460","30,710","88,295","26,485","21,265","20,480","68,230","18,320","16,205","19,085","53,610","296,375","21,890","22,825","28,120","72,835","25,120","25,435","27,460","78,015","25,770","22,210","22,155","70,135","21,175","20,155","24,220",...,"70,495","21,165","17,470","35,800","74,440","39,750","37,910","45,255","122,915","46,505","47,625","44,065","138,200","406,050","35,450","37,365","40,990","113,805","36,370","37,995","43,955","118,320","43,350","34,150","44,705","122,205","33,740","26,100","23,460","83,295","437,625","50,945","49,670","44,875","145,485","29,565","46,005","42,355","117,925","40,705","35,095","32,190","107,990","33,630","29,505","37,240","100,375","471,770","47,660","47,660"

In [11]:
df = df.replace("--",0)
df.tail(12)

,"Canada - Admissions of Permanent Residents by Country of Citizenship, January 2015 - January 2024",2015Jan,2015Feb,2015Mar,2015Q1Total,2015Apr,2015May,2015Jun,2015Q2Total,2015July,2015Aug,2015Sep,2015Q3Total,2015Oct,2015Nov,2015Dec,2015Q4total,2015YearTotal,2016Jan,2016Feb,2016Mar,2016Q1Total,2016Apr,2016May,2016Jun,2016Q2Total,2016July,2016Aug,2016Sep,2016Q3Total,2016Oct,2016Nov,2016Dec,2016Q4total,2016YearTotal,2017Jan,2017Feb,2017Mar,2017Q1Total,2017Apr,2017May,2017Jun,2017Q2Total,2017July,2017Aug,2017Sep,2017Q3Total,2017Oct,2017Nov,2017Dec,...,2021Q1Total,2021Apr,2021May,2021Jun,2021Q2Total,2021July,2021Aug,2021Sep,2021Q3Total,2021Oct,2021Nov,2021Dec,2021Q4total,2021YearTotal,2022Jan,2022Feb,2022Mar,2022Q1Total,2022Apr,2022May,2022Jun,2022Q2Total,2022July,2022Aug,2022Sep,2022Q3Total,2022Oct,2022Nov,2022Dec,2022Q4total,2022YearTotal,2023Jan,2023Feb,2023Mar,2023Q1Total,2023Apr,2023May,2023Jun,2023Q2Total,2023July,2023Aug,2023Sep,2023Q3Total,2023Oct,2023Nov,2023Dec,2023Q4total,2023YearTotal,2024Jan,2024Feb
209,Uruguay,0,0,0,10,0,10,0,10,0,10,0,10,0,5,0,15,45,0,0,10,15,0,0,5,10,10,10,0,20,0,5,0,10,55,0,0,0,5,5,0,0,10,0,0,0,0,0,0,0,...,15,0,5,5,10,10,5,5,20,10,10,5,25,75,10,5,10,25,0,0,10,15,10,0,0,15,5,0,0,5,65,10,5,10,30,0,10,10,20,10,5,0,15,0,0,0,10,75,15,15
210,Uzbekistan,5,5,25,35,15,10,20,50,15,5,25,50,20,20,20,60,190,10,5,20,35,20,25,35,80,20,25,20,65,15,10,5,30,210,10,10,10,30,10,30,30,65,10,15,5,30,15,15,25,...,40,5,10,10,25,15,5,5,30,5,10,10,25,120,5,0,10,20,0,20,15,35,10,15,0,30,15,5,5,25,115,5,15,15,40,20,20,15,55,25,20,10,60,5,20,15,40,190,25,25
211,Vanuatu,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
212,Venezuela,40,40,75,160,80,70,90,235,65,115,80,260,95,85,75,260,915,80,70,90,240,115,115,130,360,85,100,60,245,65,45,55,165,"1,010",60,70,80,210,80,75,115,270,110,85,75,270,80,75,105,...,785,250,195,195,640,170,180,220,575,175,240,205,620,"2,625",170,150,155,475,130,175,135,440,170,110,125,405,85,75,60,225,"1,545",185,125,110,420,95,145,140,380,105,145,75,325,95,50,115,265,"1,390",145,145
213,Vietnam,90,165,180,435,155,150,190,490,250,205,430,885,300,270,215,785,"2,595",220,215,290,725,205,205,255,665,250,165,185,600,160,125,175,460,"2,450",145,195,250,590,200,210,315,725,240,230,190,665,185,140,200,...,875,320,230,500,"1,045",610,540,595,"1,745",675,800,615,"2,090","5,755",575,565,580,"1,720",535,460,635,"1,630",600,490,460,"1,555",275,120,160,560,"5,460",915,865,620,"2,405",330,705,525,"1,560",580,470,355,"1,405",325,290,620,"1,235","6,605",825,825
214,"Virgin Islands, British",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
215,Western Sahara,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
216,Yemen,15,5,25,45,20,15,20,55,15,15,20,50,20,20,15,55,205,15,5,15,40,0,45,25,70,10,10,15,35,10,5,0,20,160,10,10,15,40,20,25,35,80,45,20,10,80,20,15,15,...,440,90,90,85,260,70,100,145,320,155,115,95,360,"1,380",85,80,90,255,65,90,70,230,80,35,75,190,70,35,45,150,820,80,50,45,180,30,45,80,155,55,70,50,170,45,50,55,150,650,70,70
217,Zambia,0,0,0,0,0,0,0,10,0,10,5,20,5,0,10,20,55,0,0,5,5,5,5,10,20,0,5,0,10,5,0,5,15,55,15,10,0,25,5,10,10,25,5,10,0,15,5,0,15,...,20,0,10,10,25,10,5,0,20,10,10,10,30,95,5,5,10,20,0,10,5,20,15,10,0,30,5,5,0,15,85,20,10,10,40,0,5,5,15,10,0,5,15,0,5,10,20,90,10,10
218,Zimbabwe,15,15,25,55,15,20,15,50,25,20,20,65,30,15,15,60,230,25,15,25,65,25,50,25,105,10,20,20,50,20,30,15,65,280,35,20,45,100,30,35,40,100,55,35,25,115,20,40,40,...,90,30,20,50,100,45,55,60,160,40,40,80,165,510,50,70,65,180,60,50,60,165,40,60,65,165,35,25,35,95,605,70,60,40,170,50,55,45,150,40,50,25,110,30,30,60,120,555,50,50
219,Country not stated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
220,Total,"12,910","16,440","21,770","51,125","21,165","23,895","27,025","72,090","27,770","24,350","26,770","78,890","23,990","20,855","24,890","69,735","271,840","27,280","32,035","26,925","86,235","28,125","29,460","30,710","88,295","26,485","21,265","20,480","68,230","18,320","16,205","19,085","53,610","296,375","21,890","22,825","28,120","72,835","25,120","25,435","27,460","78,015","25,770","22,210","22,155","70,135","21,175","20,155","24,220",...,"70,495","21,165","17,470","35,800","74,440","39,750","37,910","45,255","122,915","46,505","47,625","44,065","138,200","406,050","35,450","37,365","40,990","113,805","36,370","37,995","43,955","118,320","43,350","34,150","44,705","122,205","33,740","26,100","23,460","83,295","437,625","50,945","49,670","44,875","145,485","29,565","46,005","42,355","117,925","40,705","35,095","32,190","107,990","33,630","29,505","37,240","100,375","471,770","47,660","47,660"

In [12]:
df.dtypes

Canada - Admissions of Permanent Residents by Country of Citizenship, January 2015 - January 2024    object
2015Jan                                                                                              object
2015Feb                                                                                              object
2015Mar                                                                                              object
2015Q1Total                                                                                          object
                                                                                                      ...
2023Dec                                                                                              object
2023Q4total                                                                                          object
2023YearTotal                                                                                        object
2024Jan                                                                                              object
2024Feb                                                                                              object
Length: 156, dtype: object

In [13]:
df = df.astype(str)

In [14]:
df.dtypes

Canada - Admissions of Permanent Residents by Country of Citizenship, January 2015 - January 2024    object
2015Jan                                                                                              object
2015Feb                                                                                              object
2015Mar                                                                                              object
2015Q1Total                                                                                          object
                                                                                                      ...
2023Dec                                                                                              object
2023Q4total                                                                                          object
2023YearTotal                                                                                        object
2024Jan                                                                                              object
2024Feb                                                                                              object
Length: 156, dtype: object

In [15]:
#change data type to int
for column in df:
    try:
        df[column] = df[column].str.replace(",","").astype(int)
    except:
        pass

In [16]:
df.dtypes

Canada - Admissions of Permanent Residents by Country of Citizenship, January 2015 - January 2024    object
2015Jan                                                                                               int32
2015Feb                                                                                               int32
2015Mar                                                                                               int32
2015Q1Total                                                                                           int32
                                                                                                      ...
2023Dec                                                                                               int32
2023Q4total                                                                                           int32
2023YearTotal                                                                                         int32
2024Jan                                                                                               int32
2024Feb                                                                                               int32
Length: 156, dtype: object

In [17]:
df.head()

,"Canada - Admissions of Permanent Residents by Country of Citizenship, January 2015 - January 2024",2015Jan,2015Feb,2015Mar,2015Q1Total,2015Apr,2015May,2015Jun,2015Q2Total,2015July,2015Aug,2015Sep,2015Q3Total,2015Oct,2015Nov,2015Dec,2015Q4total,2015YearTotal,2016Jan,2016Feb,2016Mar,2016Q1Total,2016Apr,2016May,2016Jun,2016Q2Total,2016July,2016Aug,2016Sep,2016Q3Total,2016Oct,2016Nov,2016Dec,2016Q4total,2016YearTotal,2017Jan,2017Feb,2017Mar,2017Q1Total,2017Apr,2017May,2017Jun,2017Q2Total,2017July,2017Aug,2017Sep,2017Q3Total,2017Oct,2017Nov,2017Dec,...,2021Q1Total,2021Apr,2021May,2021Jun,2021Q2Total,2021July,2021Aug,2021Sep,2021Q3Total,2021Oct,2021Nov,2021Dec,2021Q4total,2021YearTotal,2022Jan,2022Feb,2022Mar,2022Q1Total,2022Apr,2022May,2022Jun,2022Q2Total,2022July,2022Aug,2022Sep,2022Q3Total,2022Oct,2022Nov,2022Dec,2022Q4total,2022YearTotal,2023Jan,2023Feb,2023Mar,2023Q1Total,2023Apr,2023May,2023Jun,2023Q2Total,2023July,2023Aug,2023Sep,2023Q3Total,2023Oct,2023Nov,2023Dec,2023Q4total,2023YearTotal,2024Jan,2024Feb
4,Afghanistan,90,125,220,435,135,220,195,555,250,145,375,770,270,335,265,870,2630,215,295,260,765,285,200,255,740,210,125,275,610,255,160,120,535,2650,230,375,325,930,330,210,210,750,310,280,235,820,290,405,260,...,545,140,150,180,475,180,1010,1535,2725,1130,1265,2430,4825,8570,865,1650,2075,4590,2215,2475,2145,6835,1130,1225,3520,5875,2660,2240,1545,6450,23750,715,875,1320,2905,1110,2225,1430,4765,2000,1250,2210,5460,1400,3465,2180,7045,20180,1815,1815
5,Albania,15,25,50,90,45,45,75,165,45,65,60,170,35,50,55,140,565,50,30,65,145,45,60,45,150,30,40,40,110,40,25,40,105,510,40,50,80,170,70,60,65,190,75,30,70,175,35,35,40,...,115,35,35,45,115,60,55,75,190,45,40,45,130,550,50,50,65,165,75,40,50,165,35,40,55,125,30,15,20,65,520,85,60,70,215,25,65,45,135,75,70,30,175,40,40,50,125,655,110,110
6,Algeria,80,125,235,440,255,340,280,875,310,280,355,940,225,170,175,570,2830,95,100,215,410,300,330,245,880,585,255,220,1055,190,130,150,475,2820,140,120,270,530,280,210,250,740,505,205,215,925,145,145,150,...,465,90,110,245,445,590,285,280,1155,365,315,325,1010,3080,200,360,530,1090,395,630,710,1735,1085,390,735,2205,490,300,350,1140,6175,225,265,320,805,285,510,530,1325,875,325,760,1960,540,335,280,1160,5245,400,400
7,Andorra,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,Angola,0,0,0,0,10,0,0,15,0,0,0,5,0,0,5,10,30,0,5,0,10,0,10,0,15,0,0,0,5,0,0,0,0,30,5,0,0,10,5,0,5,15,10,0,0,10,0,0,0,...,35,5,0,0,15,15,15,15,45,25,20,15,60,150,15,25,20,60,50,30,25,105,30,20,10,60,0,5,0,15,240,25,35,25,85,25,15,10,50,10,5,5,25,25,15,35,75,235,20,20

In [18]:
df = df.drop(df[(df["2015YearTotal"] <= 0) & (df["2023YearTotal"]<=0)].index)
df.tail(12)

,"Canada - Admissions of Permanent Residents by Country of Citizenship, January 2015 - January 2024",2015Jan,2015Feb,2015Mar,2015Q1Total,2015Apr,2015May,2015Jun,2015Q2Total,2015July,2015Aug,2015Sep,2015Q3Total,2015Oct,2015Nov,2015Dec,2015Q4total,2015YearTotal,2016Jan,2016Feb,2016Mar,2016Q1Total,2016Apr,2016May,2016Jun,2016Q2Total,2016July,2016Aug,2016Sep,2016Q3Total,2016Oct,2016Nov,2016Dec,2016Q4total,2016YearTotal,2017Jan,2017Feb,2017Mar,2017Q1Total,2017Apr,2017May,2017Jun,2017Q2Total,2017July,2017Aug,2017Sep,2017Q3Total,2017Oct,2017Nov,2017Dec,...,2021Q1Total,2021Apr,2021May,2021Jun,2021Q2Total,2021July,2021Aug,2021Sep,2021Q3Total,2021Oct,2021Nov,2021Dec,2021Q4total,2021YearTotal,2022Jan,2022Feb,2022Mar,2022Q1Total,2022Apr,2022May,2022Jun,2022Q2Total,2022July,2022Aug,2022Sep,2022Q3Total,2022Oct,2022Nov,2022Dec,2022Q4total,2022YearTotal,2023Jan,2023Feb,2023Mar,2023Q1Total,2023Apr,2023May,2023Jun,2023Q2Total,2023July,2023Aug,2023Sep,2023Q3Total,2023Oct,2023Nov,2023Dec,2023Q4total,2023YearTotal,2024Jan,2024Feb
205,Ukraine,120,155,160,435,155,160,205,520,230,260,280,770,245,195,180,615,2345,185,275,345,805,300,345,410,1055,290,300,290,885,225,200,180,610,3350,265,295,365,925,275,300,380,960,265,230,280,775,215,215,215,...,640,190,175,315,680,350,300,315,970,300,320,285,905,3190,275,320,795,1385,445,355,320,1120,290,260,210,760,125,110,75,315,3575,460,380,285,1125,140,300,290,730,290,240,100,630,175,120,335,630,3110,520,520
206,United Arab Emirates,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,15,0,0,0,0,0,0,0,0,0,5,0,5,0,0,0,...,5,0,0,0,0,0,0,0,0,0,0,0,5,20,0,0,0,0,0,0,5,10,5,0,0,10,0,0,0,0,25,0,0,0,5,0,10,0,15,0,0,0,0,0,0,0,0,25,0,0
207,United Kingdom and Overseas Territories,320,305,400,1025,435,460,500,1390,455,575,510,1545,550,450,400,1395,5360,605,570,625,1795,545,610,535,1690,520,480,395,1395,340,235,350,925,5805,670,490,455,1615,405,445,380,1230,340,445,370,1155,430,380,500,...,1160,470,370,775,1615,700,705,640,2045,570,630,535,1735,6555,485,545,520,1545,375,405,415,1195,415,410,370,1195,195,150,215,555,4495,790,665,520,1970,270,500,395,1165,335,345,220,895,300,255,400,955,4990,545,545
208,United States of America,455,450,470,1375,565,740,750,2055,760,855,660,2275,630,630,690,1950,7655,700,765,830,2300,810,865,885,2560,825,725,625,2175,565,430,455,1450,8485,760,715,870,2345,770,745,850,2365,655,795,600,2045,755,705,920,...,2095,775,675,1130,2580,1175,1145,1165,3490,1375,1230,1185,3790,11955,1055,1045,1130,3235,955,870,980,2805,1040,940,905,2885,550,355,590,1490,10415,1790,1400,1075,4265,590,985,835,2410,875,870,425,2170,470,510,815,1795,10640,1085,1085
209,Uruguay,0,0,0,10,0,10,0,10,0,10,0,10,0,5,0,15,45,0,0,10,15,0,0,5,10,10,10,0,20,0,5,0,10,55,0,0,0,5,5,0,0,10,0,0,0,0,0,0,0,...,15,0,5,5,10,10,5,5,20,10,10,5,25,75,10,5,10,25,0,0,10,15,10,0,0,15,5,0,0,5,65,10,5,10,30,0,10,10,20,10,5,0,15,0,0,0,10,75,15,15
210,Uzbekistan,5,5,25,35,15,10,20,50,15,5,25,50,20,20,20,60,190,10,5,20,35,20,25,35,80,20,25,20,65,15,10,5,30,210,10,10,10,30,10,30,30,65,10,15,5,30,15,15,25,...,40,5,10,10,25,15,5,5,30,5,10,10,25,120,5,0,10,20,0,20,15,35,10,15,0,30,15,5,5,25,115,5,15,15,40,20,20,15,55,25,20,10,60,5,20,15,40,190,25,25
212,Venezuela,40,40,75,160,80,70,90,235,65,115,80,260,95,85,75,260,915,80,70,90,240,115,115,130,360,85,100,60,245,65,45,55,165,1010,60,70,80,210,80,75,115,270,110,85,75,270,80,75,105,...,785,250,195,195,640,170,180,220,575,175,240,205,620,2625,170,150,155,475,130,175,135,440,170,110,125,405,85,75,60,225,1545,185,125,110,420,95,145,140,380,105,145,75,325,95,50,115,265,1390,145,145
213,Vietnam,90,165,180,435,155,150,190,490,250,205,430,885,300,270,215,785,2595,220,215,290,725,205,205,255,665,250,165,185,600,160,125,175,460,2450,145,195,250,590,200,210,315,725,240,230,190,665,185,140,200,...,875,320,230,500,1045,610,540,595,1745,675,800,615,2090,5755,575,565,580,1720,535,460,635,1630,600,490,460,1555,275,120,160,560,5460,915,865,620,2405,330,705,525,1560,580,470,355,1405,325,290,620,1235,6605,825,825
216,Yemen,15,5,25,45,20,15,20,55,15,15,20,50,20,20,15,55,205,15,5,15,40,0,45,25,70,10,10,15,35,10,5,0,20,160,10,10,15,40,20,25,35,80,45,20,10,80,20,15,15,...,440,90,90,85,260,70,100,145,320,155,115,95,360,1380,85,80,90,255,65,90,70,230,80,35,75,190,70,35,45,150,820,80,50,45,180,30,45,80,155,55,70,50,170,45,50,55,150,650,70,70
217,Zambia,0,0,0,0,0,0,0,10,0,10,5,20,5,0,10,20,55,0,0,5,5,5,5,10,20,0,5,0,10,5,0,5,15,55,15,10,0,25,5,10,10,25,5,10,0,15,5,0,15,...,20,0,10,10,25,10,5,0,20,10,10,10,30,95,5,5,10,20,0,10,5,20,15,10,0,30,5,5,0,15,85,20,10,10,40,0,5,5,15,10,0,5,15,0,5,10,20,90,10,10
218,Zimbabwe,15,15,25,55,15,20,15,50,25,20,20,65,30,15,15,60,230,25,15,25,65,25,50,25,105,10,20,20,50,20,30,15,65,280,35,20,45,100,30,35,40,100,55,35,25,115,20,40,40,...,90,30,20,50,100,45,55,60,160,40,40,80,165,510,50,70,65,180,60,50,60,165,40,60,65,165,35,25,35,95,605,70,60,40,170,50,55,45,150,40,50,25,110,30,30,60,120,555,50,50
220,Total,12910,16440,21770,51125,21165,23895,27025,72090,27770,24350,26770,78890,23990,20855,24890,69735,271840,27280,32035,26925,86235,28125,29460,30710,88295,26485,21265,20480,68230,18320,16205,19085,53610,296375,21890,22825,28120,72835,25120,25435,27460,78015,25770,22210,22155,70135,21175,20155,24220,...,70495,21165,17470,35800,74440,39750,37910,45255,122915,46505,47625,44065,138200,406050,35450,37365,40990,113805,36370,37995,43955,118320,43350,34150,44705,122205,33740,26100,23460,83295,437625,50945,49670,44875,145485,29565,46005,42355,117925,40705,35095,32190,107990,33630,29505,37240,100375,471770,47660,47660

In [21]:
df.head(12)

,"Canada - Admissions of Permanent Residents by Country of Citizenship, January 2015 - January 2024",2015Jan,2015Feb,2015Mar,2015Q1Total,2015Apr,2015May,2015Jun,2015Q2Total,2015July,2015Aug,2015Sep,2015Q3Total,2015Oct,2015Nov,2015Dec,2015Q4total,2015YearTotal,2016Jan,2016Feb,2016Mar,2016Q1Total,2016Apr,2016May,2016Jun,2016Q2Total,2016July,2016Aug,2016Sep,2016Q3Total,2016Oct,2016Nov,2016Dec,2016Q4total,2016YearTotal,2017Jan,2017Feb,2017Mar,2017Q1Total,2017Apr,2017May,2017Jun,2017Q2Total,2017July,2017Aug,2017Sep,2017Q3Total,2017Oct,2017Nov,2017Dec,...,2021Q1Total,2021Apr,2021May,2021Jun,2021Q2Total,2021July,2021Aug,2021Sep,2021Q3Total,2021Oct,2021Nov,2021Dec,2021Q4total,2021YearTotal,2022Jan,2022Feb,2022Mar,2022Q1Total,2022Apr,2022May,2022Jun,2022Q2Total,2022July,2022Aug,2022Sep,2022Q3Total,2022Oct,2022Nov,2022Dec,2022Q4total,2022YearTotal,2023Jan,2023Feb,2023Mar,2023Q1Total,2023Apr,2023May,2023Jun,2023Q2Total,2023July,2023Aug,2023Sep,2023Q3Total,2023Oct,2023Nov,2023Dec,2023Q4total,2023YearTotal,2024Jan,2024Feb
4,Afghanistan,90,125,220,435,135,220,195,555,250,145,375,770,270,335,265,870,2630,215,295,260,765,285,200,255,740,210,125,275,610,255,160,120,535,2650,230,375,325,930,330,210,210,750,310,280,235,820,290,405,260,...,545,140,150,180,475,180,1010,1535,2725,1130,1265,2430,4825,8570,865,1650,2075,4590,2215,2475,2145,6835,1130,1225,3520,5875,2660,2240,1545,6450,23750,715,875,1320,2905,1110,2225,1430,4765,2000,1250,2210,5460,1400,3465,2180,7045,20180,1815,1815
5,Albania,15,25,50,90,45,45,75,165,45,65,60,170,35,50,55,140,565,50,30,65,145,45,60,45,150,30,40,40,110,40,25,40,105,510,40,50,80,170,70,60,65,190,75,30,70,175,35,35,40,...,115,35,35,45,115,60,55,75,190,45,40,45,130,550,50,50,65,165,75,40,50,165,35,40,55,125,30,15,20,65,520,85,60,70,215,25,65,45,135,75,70,30,175,40,40,50,125,655,110,110
6,Algeria,80,125,235,440,255,340,280,875,310,280,355,940,225,170,175,570,2830,95,100,215,410,300,330,245,880,585,255,220,1055,190,130,150,475,2820,140,120,270,530,280,210,250,740,505,205,215,925,145,145,150,...,465,90,110,245,445,590,285,280,1155,365,315,325,1010,3080,200,360,530,1090,395,630,710,1735,1085,390,735,2205,490,300,350,1140,6175,225,265,320,805,285,510,530,1325,875,325,760,1960,540,335,280,1160,5245,400,400
8,Angola,0,0,0,0,10,0,0,15,0,0,0,5,0,0,5,10,30,0,5,0,10,0,10,0,15,0,0,0,5,0,0,0,0,30,5,0,0,10,5,0,5,15,10,0,0,10,0,0,0,...,35,5,0,0,15,15,15,15,45,25,20,15,60,150,15,25,20,60,50,30,25,105,30,20,10,60,0,5,0,15,240,25,35,25,85,25,15,10,50,10,5,5,25,25,15,35,75,235,20,20
9,Antigua and Barbuda,0,5,10,20,0,0,5,10,5,5,5,20,0,0,0,5,55,0,10,0,10,0,0,0,10,5,0,10,15,0,0,0,10,45,5,10,5,25,10,10,0,20,10,0,0,15,5,0,10,...,25,5,5,5,20,10,5,20,35,15,15,15,40,120,10,5,10,25,10,10,5,25,15,10,10,35,10,0,5,20,105,25,10,10,45,10,5,10,30,10,15,5,30,0,5,5,15,120,0,0
10,Argentina,10,15,15,40,25,25,20,65,25,20,20,65,10,20,25,55,225,30,15,20,70,35,40,20,100,20,25,15,60,20,10,10,35,265,30,15,15,60,15,15,20,50,25,15,20,55,20,20,25,...,70,20,20,50,90,25,40,35,105,50,45,55,145,410,30,35,55,120,30,25,25,80,45,35,30,110,15,20,15,50,360,55,50,45,150,30,60,65,155,30,40,10,80,25,15,65,100,485,55,55
11,Armenia,10,10,10,25,20,15,40,75,45,50,40,130,25,15,30,70,305,10,20,20,50,35,15,40,90,35,45,60,140,45,10,20,70,350,10,30,30,70,30,15,30,75,30,5,15,50,20,15,20,...,20,5,15,5,25,10,5,15,35,5,0,10,20,95,5,20,0,30,15,5,15,40,15,10,10,30,20,5,15,40,140,15,15,15,40,5,15,35,55,30,15,25,70,30,25,15,70,240,10,10
12,Australia,95,70,100,265,145,160,110,415,135,140,140,420,140,125,110,375,1470,155,140,170,465,205,180,185,570,155,160,95,405,90,95,80,265,1705,165,185,165,510,140,145,130,410,125,160,165,450,155,150,185,...,355,120,125,275,520,225,215,220,660,205,180,155,540,2080,165,130,155,450,115,120,135,375,120,100,80,300,45,40,60,145,1265,190,190,150,530,75,120,90,285,95,110,50,255,50,50,90,190,1260,110,110
13,Austria,10,10,5,25,10,10,15,40,5,5,15,30,10,0,10,25,120,5,15,5,25,15,10,10,30,5,10,5,20,10,10,0,20,100,10,15,5,30,10,5,10,25,10,5,10,25,0,10,15,...,15,5,10,15,30,10,15,15,40,10,5,10,25,115,10,15,10,35,10,10,5,25,0,10,10,25,0,0,10,15,100,25,15,10,45,10,5,5,20,15,0,0,20,0,0,5,10,100,15,15
14,Azerbaijan,5,10,0,20,0,0,10,20,15,30,5,50,10,10,0,20,110,5,20,10,35,15,20,15,45,10,0,0,15,5,5,10,20,115,0,10,5,20,10,5,10,20,15,5,10,30,15,15,10,...,155,25,15,30,70,50,30,45,125,70,55,40,160,505,35,25,40,95,40,30,40,110,30,25,30,90,25,15,15,60,350,40,25,25,90,10,20,20,50,15,20,20,55,10,10,30,50,245,25,25
16,"Bahama Islands, The",0,10,10,20,0,5,0,10,10,5,10,30,0,5,10,20,80,5,10,5,20,10,10,10,25,10,10,0,20,0,10,0,15,80,0,15,15,35,10,15,10,30,5,15,5,30,10,5,20,...,70,20,20,40,85,30,35,40,105,35,45,30,110,370,25,40,35,100,30,20,30,85,30,25,15,75,10,0,10,20,275,75,75,25,175,20,35,35,85,30,30,15,75,25,15,25,70,400,75,75
17,Bahrain,0,5,0,10,5,0,5,10,0,0,0,0,0,10,0,15,35,5,0,0,5,0,0,0,5,0,0,0,5,0,0,0,0,20,10,0,0,10,5,0,0,10,0,0,10,10,0,0,0,...,5,0,0,0,5,0,5,0,10,0,0,0,5,25,0,0,0,5,0,0,0,5,0,0,0,5,0,0,0,0,20,0,0,0,0,0,0,0,10,0,0,0,10,0,0,0,5,30,0,0

In [22]:
df.to_excel("cleaned data.xlsx",index = None)